name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build 🔧
        run: python3 build_plugin.py --out-dir dist dw235 "plugins/*.js"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.js
