name: Release
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0

      - name: Build 🔧
        run: python3 build_plugin.py --out-dir dist dw235 "plugins/*.js"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          target_commitish: main
          prerelease: false
          files: dist/*.js
